package view;

import dao.Pessoa;
import dao.ConectaBanco;
import dao.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

public final class JFCliente extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();

    /**
     * Creates new form JFVeiculo
     */
    public JFCliente() {
        initComponents();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        conecta.conecte();

        preenchaTabela();
    }

    public void preenchaTabela() {
        // cria uma lista com as colunas do componente JTable
        String[] colunas = new String[]{"Cód.", "Nome", "Idade", "CPF", "CNH"};

        // cria uma estrutura para abrigar a lista de clientes do banco de dados
        ArrayList dados = new ArrayList();

        // sql para listar pessoa_id e nome da tabela pessoa
        // e listar curso e série da tabela cliente
        conecta.executeSQL("select * from v_cliente order by pessoa_id"
        );
        try {
            // identifica o primeiro item do recordset
            conecta.rs.first();
            do {
                // insere os dados encontrados em um ArrayList
                dados.add(new Object[]{
                    conecta.rs.getInt("pessoa_id"),
                    conecta.rs.getString("nome"),
                    conecta.rs.getString("cnh"),
                    conecta.rs.getString("cpf"),
                    conecta.rs.getInt("idade")
                });
            } while (conecta.rs.next()); // a cada item no recordset
        } catch (SQLException ex) {
            Logger.getLogger(JFCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        tblCliente.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdade = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtCNH = new javax.swing.JTextField();
        labelSair = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnNovo = new javax.swing.JLabel();
        btnGravar = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JLabel();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        txtIdade.setText("Idade");
        txtIdade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdadeFocusLost(evt);
            }
        });
        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdade);
        txtIdade.setBounds(440, 70, 310, 30);

        txtNome.setText("Nome");
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(70, 70, 310, 30);

        txtCPF.setText("CPF");
        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFocusLost(evt);
            }
        });
        getContentPane().add(txtCPF);
        txtCPF.setBounds(70, 130, 310, 30);

        txtCNH.setText("CNH");
        txtCNH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCNHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCNHFocusLost(evt);
            }
        });
        getContentPane().add(txtCNH);
        txtCNH.setBounds(440, 130, 310, 30);

        labelSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        labelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSairMouseClicked(evt);
            }
        });
        getContentPane().add(labelSair);
        labelSair.setBounds(320, 200, 50, 50);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "Idade", "CPF", "CNH"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 690, 300);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo);
        btnNovo.setBounds(160, 200, 40, 50);

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        btnGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarMouseClicked(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(70, 200, 50, 50);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(240, 200, 40, 50);

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.png"))); // NOI18N
        labelFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelFundo);
        labelFundo.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int pessoa_id;

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {
        // recupera o id do item selecionado
        int i = tblCliente.getSelectedRow();
        // recupera o modelo do JTable livro
        TableModel model = tblCliente.getModel();
        // recupera o id do livro
        this.pessoa_id = Integer.parseInt(model.getValueAt(i, 0).toString());
        // preenche o formulário com os valores da linha
        txtNome.setText(model.getValueAt(i, 1).toString());
        txtIdade.setText(model.getValueAt(i, 2).toString());
        txtCPF.setText(model.getValueAt(i, 3).toString());
        txtCNH.setText(model.getValueAt(i, 4).toString());

        // habilita o botão excluir
        btnExcluir.setEnabled(true);
    }

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void labelSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSairMouseClicked
        //fecha a janela
        dispose();
    }//GEN-LAST:event_labelSairMouseClicked

    private void txtIdadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdadeFocusGained
        //limpa a caixa de texto
        if (txtIdade.getText().
                equals("Idade")) {
            txtIdade.setText("");
        }
    }//GEN-LAST:event_txtIdadeFocusGained

    private void txtCNHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCNHFocusGained
        //limpa a caixa de texto
        if (txtCNH.getText().
                equals("CNH")) {
            txtCNH.setText("");
        }
    }//GEN-LAST:event_txtCNHFocusGained

    private void txtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusGained
        //limpa a caixa de texto
        if (txtCPF.getText().
                equals("CPF")) {
            txtCPF.setText("");
        }
    }//GEN-LAST:event_txtCPFFocusGained

    private void txtIdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdadeFocusLost
        //caso o usuaario nao entre com informaçoes devolve o valor inicial
        if (txtIdade.getText().equals("")) {
            txtIdade.setText("Idade");
        }
    }//GEN-LAST:event_txtIdadeFocusLost

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        //caso o usuaario nao entre com informaçoes devolve o valor inicial
        if (txtNome.getText().equals("")) {
            txtNome.setText("Nome");
        }

    }//GEN-LAST:event_txtNomeFocusLost

    private void txtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusLost
        //caso o usuaario nao entre com informaçoes devolve o valor inicial
        if (txtCPF.getText().equals("")) {
            txtCPF.setText("CPF");
        }
    }//GEN-LAST:event_txtCPFFocusLost

    private void txtCNHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCNHFocusLost
        //caso o usuaario nao entre com informaçoes devolve o valor inicial
        if (txtCNH.getText().equals("")) {
            txtCNH.setText("CNH");
        }
    }//GEN-LAST:event_txtCNHFocusLost

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        //limpa a caixa de texto
        if (txtNome.getText().
                equals("Nome")) {
            txtNome.setText("");
        }
    }//GEN-LAST:event_txtNomeMouseClicked

    private void btnGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarMouseClicked
        Pessoa cliente = new Pessoa();

        // seta os atributos da classe cliente
        try {
            // caso algum registro do JTable tenha sido selecionado
            if (this.pessoa_id != 0) {
                // seta o valor do atributo
                cliente.setPessoaId(this.pessoa_id);
            }

            cliente.setNome(txtNome.getText());
            cliente.setIdade(Integer.parseInt(txtIdade.getText()));
            cliente.setCpf(txtCPF.getText());
            cliente.setCnh(txtCNH.getText());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informe os valores corretamente.");
        }

        // invoca o método que salva o registro de cliente no BD
        cliente.salve();

        // preenche a tabela com os registos atualizados
        preenchaTabela();
    }//GEN-LAST:event_btnGravarMouseClicked

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        // reseta todos os componentes
        this.pessoa_id = 0;
        txtNome.setText("");
        txtIdade.setText("");
        txtCPF.setText("");
        txtCNH.setText("");

    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // cria objeto da classe
        Pessoa cliente = new Pessoa();
        // determina o cliente que será removido
        cliente.setPessoaId(this.pessoa_id);
        // invoca o método que remove o registro de cliente
        cliente.delete();

        // atualiza o JTable com os itens atualizados
        preenchaTabela();


    }//GEN-LAST:event_btnExcluirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExcluir;
    private javax.swing.JLabel btnGravar;
    private javax.swing.JLabel btnNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelSair;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtCNH;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

}
