package view;

import dao.ConectaBanco;
import dao.Veiculo;
import dao.ModeloTabela;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public final class JFVeiculo extends javax.swing.JFrame {

    // cria objeto da classe ConectaBanco
    ConectaBanco conecta = new ConectaBanco();

    /**
     * Creates new form JFVeiculo
     */
    public JFVeiculo() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // conectar com o banco de dados
        conecta.conecte();

        preenchaTabela();

    }

    public void preenchaTabela() {
        
        String[] colunas = new String[]{"Cód.", "Modelo", "Marca",
            "Placa", "Valor"};

        ArrayList dados = new ArrayList();

        conecta.executeSQL("select * from veiculo order by marca");
        
        Veiculo veiculo = new Veiculo();
        
        ResultSet rs = veiculo.listeVeiculos();

        try {
            conecta.rs.first();

            do {

                dados.add(new Object[]{
                    conecta.rs.getInt("veiculo_id"),
                    conecta.rs.getString("modelo"),
                    conecta.rs.getString("marca"),
                    conecta.rs.getString("placa"),
                    conecta.rs.getString("valor_locacao_dia")
                });

            } while (conecta.rs.next());

        } catch (SQLException ex) {
            Logger.getLogger(JFVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        tblVeiculos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtValorLocacaoDia = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JLabel();
        btnNovo = new javax.swing.JLabel();
        btnGravar = new javax.swing.JLabel();
        btnSair = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeiculos = new javax.swing.JTable();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        txtModelo.setText("Modelo");
        txtModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtModeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModeloFocusLost(evt);
            }
        });
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        getContentPane().add(txtModelo);
        txtModelo.setBounds(440, 70, 310, 30);

        txtMarca.setText("Marca");
        txtMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMarcaFocusLost(evt);
            }
        });
        txtMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMarcaMouseClicked(evt);
            }
        });
        getContentPane().add(txtMarca);
        txtMarca.setBounds(70, 70, 310, 30);

        txtValorLocacaoDia.setText("Valor da diaria");
        txtValorLocacaoDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorLocacaoDiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorLocacaoDiaFocusLost(evt);
            }
        });
        getContentPane().add(txtValorLocacaoDia);
        txtValorLocacaoDia.setBounds(440, 130, 310, 30);

        txtPlaca.setText("Placa");
        txtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPlacaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaFocusLost(evt);
            }
        });
        getContentPane().add(txtPlaca);
        txtPlaca.setBounds(70, 130, 310, 30);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(240, 200, 40, 50);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });
        getContentPane().add(btnNovo);
        btnNovo.setBounds(160, 200, 40, 50);

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        btnGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarMouseClicked(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(70, 200, 50, 50);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(320, 200, 50, 50);

        tblVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Modelo", "Marca", "Placa", "Valor dia"
            }
        ));
        jScrollPane1.setViewportView(tblVeiculos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 690, 300);

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.png"))); // NOI18N
        labelFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelFundo);
        labelFundo.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int veiculoId = -1;
    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMarcaMouseClicked
        //limpa a caixa de texto
        if (txtMarca.getText().
                equals("Marca")) {
            txtMarca.setText("");
        }
    }//GEN-LAST:event_txtMarcaMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        //fecha a janela
        dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void txtModeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModeloFocusGained
        //limpa a caixa de texto
        if (txtModelo.getText().
                equals("Modelo")) {
            txtModelo.setText("");
        }
    }//GEN-LAST:event_txtModeloFocusGained

    private void txtValorLocacaoDiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorLocacaoDiaFocusGained
        //limpa a caixa de texto
        if (txtValorLocacaoDia.getText().
                equals("Valor da diaria")) {
            txtValorLocacaoDia.setText("");
        }
    }//GEN-LAST:event_txtValorLocacaoDiaFocusGained

    private void txtMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMarcaFocusLost
        //caso o usuaario nao entre com informaçoes devolve o valor inicial
        if (txtMarca.getText().equals("")) {
            txtMarca.setText("Marca");
        }
    }//GEN-LAST:event_txtMarcaFocusLost

    private void txtModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModeloFocusLost
        //caso o usuaario nao entre com informaçoes devolve o valor inicial
        if (txtModelo.getText().equals("")) {
            txtModelo.setText("Modelo");
        }
    }//GEN-LAST:event_txtModeloFocusLost

    private void txtValorLocacaoDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorLocacaoDiaFocusLost
        //caso o usuaario nao entre com informaçoes devolve o valor inicial
        if (txtValorLocacaoDia.getText().equals("")) {
            txtValorLocacaoDia.setText("Valor da diaria");
        }
    }//GEN-LAST:event_txtValorLocacaoDiaFocusLost

    private void txtPlacaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusGained
        //limpa a caixa de texto
        if (txtPlaca.getText().
                equals("Placa")) {
            txtPlaca.setText("");
        }
    }//GEN-LAST:event_txtPlacaFocusGained

    private void txtPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusLost
        //caso o usuaario nao entre com informaçoes devolve o valor inicial
        if (txtPlaca.getText().equals("")) {
            txtPlaca.setText("Placa");
        }
    }//GEN-LAST:event_txtPlacaFocusLost

    private void btnGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarMouseClicked
        // cria um objeto vazio da classe veiculo
        Veiculo veiculo = new Veiculo();

        // seta os atributos da classe veiculo com os valores 
        // dos campos do formulário
        try {

            if (this.veiculoId != -1) {
                veiculo.setVeiculoId(this.veiculoId);
            }

            veiculo.setMarca(txtMarca.getText());
            veiculo.setModelo(txtModelo.getText());
            veiculo.setPlaca(txtPlaca.getText());
            veiculo.setValorLocacaoDia(Double.parseDouble(txtValorLocacaoDia.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Informe os valores corretamente.");
        }

        // registra veiculo na tabela
        veiculo.salve();

        this.preenchaTabela();
        
       
    }//GEN-LAST:event_btnGravarMouseClicked

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        this.veiculoId = -1;
        txtMarca.setText("");
        txtModelo.setText("");
        txtPlaca.setText("");
        txtValorLocacaoDia.setText("");
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // cria um objeto da classe livro
        Veiculo veiculo = new Veiculo();
        veiculo.setVeiculoId(this.veiculoId);

        // chama o método que efetua a exclusão do reistro de livro
        veiculo.delete();

        // lista novamente os livros da tabela
        preenchaTabela();
    }//GEN-LAST:event_btnExcluirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFVeiculo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExcluir;
    private javax.swing.JLabel btnGravar;
    private javax.swing.JLabel btnNovo;
    private javax.swing.JLabel btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JTable tblVeiculos;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtValorLocacaoDia;
    // End of variables declaration//GEN-END:variables

   
}
