/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Salario;

import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class JFSalario extends javax.swing.JFrame {

    /**
     * Creates new form JFSalario
     */
    public JFSalario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salarioBruto = new javax.swing.JLabel();
        numeroDependentes = new javax.swing.JLabel();
        txtSalarioBruto = new javax.swing.JTextField();
        txtNumeroDependentes = new javax.swing.JTextField();
        Calcula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salarioBruto.setText("Salário Bruto:");

        numeroDependentes.setText("Número de Dependentes:");

        txtSalarioBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioBrutoActionPerformed(evt);
            }
        });

        Calcula.setText("Calcular");
        Calcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Calcula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroDependentes)
                            .addComponent(salarioBruto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumeroDependentes, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(txtSalarioBruto))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarioBruto)
                    .addComponent(txtSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDependentes)
                    .addComponent(txtNumeroDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Calcula, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculaActionPerformed
        //cria objeto da classe salarioLiquido
        SalarioLiquido salarioliquido = new SalarioLiquido();
        
        try{
            
            //atribui o valor do componente txtSalarioBruto ao atributo
            //salarioBruto do objeto salarioLiquido
            salarioliquido.setSalarioBruto ( Double.parseDouble( txtSalarioBruto.getText() ) );
            salarioliquido.setNumeroDependentes ( Integer.parseInt(txtNumeroDependentes.getText() ));
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Informe corretamente todos os campos!");
        }
        
        if ( salarioliquido.getNumeroDependentes() <= 1 ){
            salarioliquido.setValorDesconto( 0.1 );
        } else if ( salarioliquido.getNumeroDependentes() == 2 ){
            salarioliquido.setValorDesconto( 0.07 );
        } else if ( salarioliquido.getNumeroDependentes() > 2 && salarioliquido.getNumeroDependentes() <= 4 ){
            salarioliquido.setValorDesconto( 0.05 );
        } else {
            salarioliquido.setValorDesconto( 0.01 );
        }
        
        //obter o salario liquido
        salarioliquido.setSalarioLiquido();
        
        JOptionPane.showMessageDialog(null, "Salario Bruto: " + salarioliquido.getSalarioBruto() + 
                                            "\nValor do desconto: " + salarioliquido.getValorDesconto() + 
                                            "\nSalario liquido: " + salarioliquido.getSalarioLiquido());
        
    }//GEN-LAST:event_CalculaActionPerformed

    private void txtSalarioBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioBrutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFSalario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcula;
    private javax.swing.JLabel numeroDependentes;
    private javax.swing.JLabel salarioBruto;
    private javax.swing.JTextField txtNumeroDependentes;
    private javax.swing.JTextField txtSalarioBruto;
    // End of variables declaration//GEN-END:variables
}
