/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Aluno;
import dao.Emprestimo;
import dao.Livro;
import dao.ModeloTabela;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Everaldo Ribeiro
 */
public class JFEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form JFEmprestimo
     */
    public JFEmprestimo() throws SQLException {

        initComponents();

        // incluir uma máscara de data
        try {
            MaskFormatter dateMask = new MaskFormatter("##/##/####");
            dateMask.install(txtDataEmprestimo);

            MaskFormatter dateMask2 = new MaskFormatter("##/##/####");
            dateMask2.install(txtDataDevolucao);
        } catch (Exception e) {
        }

        this.populeCbbAluno();

        this.populeCbbLivro();

        this.preenchaTabela();
    }

    public void preenchaTabela() {
        String[] colunas = new String[]{"Cód.", "Aluno", "Livro", 
            "Dt. Emp.", "Dt. Dev."};

        ArrayList dados = new ArrayList();

        Emprestimo emprestimo = new Emprestimo();
        ResultSet rs = emprestimo.listeEmprestimos();

        try {
            rs.first();
            do {
                dados.add(new Object[]{
                    rs.getInt("emprestimo_id"),
                    rs.getString("nome"),
                    rs.getString("titulo"),
                    rs.getString("data_emprestimo"),
                    rs.getString("data_devolucao")
                });
            } while (rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao preencer "
                    + "a tabela");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tblEmprestimo.setModel(modelo);
    }

    // criar uma lista de objetos de aluno
    ArrayList<Aluno> listaAluno = new ArrayList<Aluno>();

    public void populeCbbAluno() throws SQLException {
        // cria uma instancia da classe aluno
        Aluno aluno = new Aluno();
        ResultSet rs = aluno.listeAlunos();

        // enquanto existir um próximo registro
        while (rs.next()) {

            // cria um novo objeto da classe aluno
            aluno = new Aluno();
            // determina os atributos nome e aluno_id do objeto
            aluno.setNome(rs.getString("nome"));
            aluno.setAlunoId(rs.getInt("aluno_id"));

            // adiciona à lista de objetos de alunos o objeto atual
            listaAluno.add(aluno);

            // determina o valor do cbbAluno
            cbbAluno.addItem(aluno.getNome());
        }
    }

    // cria uma lista de objetos de Livro
    ArrayList<Livro> listaLivro = new ArrayList<Livro>();

    public void populeCbbLivro() throws SQLException {
        // cria uma instancia da classe livro
        Livro livro = new Livro();
        ResultSet rs = livro.listeLivros();

        // enquanto existir um próximo registro
        while (rs.next()) {

            // cria um novo objeto da classe livro
            livro = new Livro();
            // determina os atributos titulo e livro_id do objeto
            livro.setTitulo(rs.getString("titulo"));
            livro.setLivroId(rs.getInt("livro_id"));

            // adiciona à lista de objetos de livros o objeto atual
            listaLivro.add(livro);

            // determina o valor do cbbLivro
            cbbLivro.addItem(livro.getTitulo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbAluno = new javax.swing.JComboBox();
        cbbLivro = new javax.swing.JComboBox();
        btnGravar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimo = new javax.swing.JTable();
        txtDataEmprestimo = new javax.swing.JFormattedTextField();
        txtDataDevolucao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Aluno:");

        jLabel2.setText("Data de empréstimo:");

        jLabel3.setText("Livro:");

        jLabel4.setText("Data de devolução:");

        cbbAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbAlunoActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Aluno", "Livro", "Dt. Emp.", "Dt. Dev."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmprestimo);

        txtDataDevolucao.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbLivro, 0, 438, Short.MAX_VALUE)
                            .addComponent(cbbAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbbAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnNovo)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        int alunoId = listaAluno.get(cbbAluno.getSelectedIndex()).getAlunoId();
        int livroId = listaLivro.get(cbbLivro.getSelectedIndex()).getLivroId();
        String dataEmprestimo = 
            txtDataEmprestimo.getText().substring(6, 10) + "-"
          + txtDataEmprestimo.getText().substring(3, 5) + "-"
          + txtDataEmprestimo.getText().substring(0, 2);
        String dataDevolucao = null;
        if (this.emprestimoId != -1) {
            dataDevolucao = txtDataDevolucao.getText().substring(6, 10) + "-"
          + txtDataDevolucao.getText().substring(3, 5) + "-"
          + txtDataDevolucao.getText().substring(0, 2);
        }
        // cria um objeto da classe emprestimo
        Emprestimo emprestimo = new Emprestimo(this.emprestimoId, 
            dataEmprestimo, dataDevolucao, alunoId, livroId);
        // invoca o método que persite as informações para o banco de dados
        emprestimo.salve();
        // preenche o componente JTable com os registros atualizados
        this.preenchaTabela();

        btnNovoActionPerformed(null);
    }//GEN-LAST:event_btnGravarActionPerformed

    public int emprestimoId = -1;

    private void tblEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmprestimoMouseClicked
        // recupera o índice da linha selecionada
        int i = tblEmprestimo.getSelectedRow();
        // criar um objeto da classe tablemodel
        TableModel model = tblEmprestimo.getModel();
        this.emprestimoId = Integer.parseInt( model.getValueAt(i, 0).toString() );

        // desabilita os campos que não podem ser alterados
        cbbAluno.setEnabled(false);
        cbbLivro.setEnabled(false);
        txtDataEmprestimo.setEnabled(false);
        txtDataDevolucao.setEnabled(true);
        btnExcluir.setEnabled(true);

        // povoa o formulário
        cbbAluno.setSelectedItem( model.getValueAt(i, 1).toString() );
        cbbLivro.setSelectedItem( model.getValueAt(i, 2).toString() );
        txtDataEmprestimo.setText( model.getValueAt(i, 3).toString() );
        txtDataDevolucao.setText( model.getValueAt(i, 4).toString() );
    }//GEN-LAST:event_tblEmprestimoMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.emprestimoId = -1;
        cbbAluno.setEnabled(true);
        cbbLivro.setEnabled(true);
        txtDataEmprestimo.setEnabled(true);
        txtDataDevolucao.setEnabled(false);
        btnExcluir.setEnabled(false);

        cbbAluno.setSelectedIndex(0);
        cbbLivro.setSelectedIndex(0);
        txtDataEmprestimo.setValue("");
        txtDataDevolucao.setValue("");

        try {
            MaskFormatter dateMask = new MaskFormatter("##/##/####");
            dateMask.install(txtDataEmprestimo);

            MaskFormatter dateMask2 = new MaskFormatter("##/##/####");
            dateMask2.install(txtDataDevolucao);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Emprestimo emprestimo = new Emprestimo();
        emprestimo.setEmprestimoId(this.emprestimoId);
        emprestimo.delete();
        this.preenchaTabela();
        btnNovoActionPerformed(null);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbbAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFEmprestimo().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox cbbAluno;
    private javax.swing.JComboBox cbbLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmprestimo;
    private javax.swing.JFormattedTextField txtDataDevolucao;
    private javax.swing.JFormattedTextField txtDataEmprestimo;
    // End of variables declaration//GEN-END:variables
}
